### ISSUE TITLE
Error when running output_image = optics(particle).plot()

### ISSUE THREAD

**Issue by giovannivolpe** [BenjaminMidtvedt/DeepTrack#24]
When running: 
output_image = optics(particle).plot()

I get this error:
../deeptrack/optics.py:136: RuntimeWarning: invalid value encountered in power
  pupil = (RHO < 1) / ((1 - NA**2 / refractive_index_medium**2 * RHO)**0.25)
../deeptrack/optics.py:140: RuntimeWarning: invalid value encountered in sqrt
  z_shift = 2 * np.pi * refractive_index_medium/wavelength * (1 - NA**2 / refractive_index_medium**2 * RHO)**0.5 * pixel_size * defocus

Please, check

**Comment by BenjaminMidtvedt** [comment]
This should be fixed in the open pull request #25
