### ISSUE TITLE
Error in tutorial tracking_point_particles

### ISSUE THREAD

**Issue by hsaga** [BenjaminMidtvedt/DeepTrack#26]
There is an error in the second last cell:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-1187ffd78a8f> in <module>
      1 from deeptrack.generators import Generator
----> 2 from deeptrack.models import convolutional
      3 
      4 
      5 G = Generator()

~/Documents/Projects/Neural networks/DeepTrack Benjamin/DeepTrack-master/deeptrack/models.py in <module>
      1 from tensorflow.keras import models, layers, optimizers
----> 2 from deeptrack.losses import nd_mean_absolute_error
      3 
      4 
      5 

~/Documents/Projects/Neural networks/DeepTrack Benjamin/DeepTrack-master/deeptrack/losses.py in <module>
     18 
     19 for keras_loss_function in _COMPATIBLE_LOSS_FUNCTIONS:
---> 20     deeptrack_loss_function = flatten(keras_loss_function)
     21     globals()[deeptrack_loss_function.__name__] = deeptrack_loss_function
     22 

NameError: name 'flatten' is not defined

**Comment by BenjaminMidtvedt** [comment]
Should be fixed as latest merge
