### ISSUE TITLE
Error in tutorial multi_particle_tracking

### ISSUE THREAD

**Issue by hsaga** [BenjaminMidtvedt/DeepTrack#28]
Error in the third last cell (same as in the other tutorial):

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-67a6da30e8c6> in <module>
----> 1 from deeptrack.models import unet
      2 from deeptrack.losses import weighted_crossentropy, sigmoid, flatten
      3 from deeptrack.generators import Generator
      4 
      5 import tensorflow.keras.backend as K

~/Documents/Projects/Neural networks/DeepTrack Benjamin/DeepTrack-master/deeptrack/models.py in <module>
      1 from tensorflow.keras import models, layers, optimizers
----> 2 from deeptrack.losses import nd_mean_absolute_error
      3 
      4 
      5 

~/Documents/Projects/Neural networks/DeepTrack Benjamin/DeepTrack-master/deeptrack/losses.py in <module>
     18 
     19 for keras_loss_function in _COMPATIBLE_LOSS_FUNCTIONS:
---> 20     deeptrack_loss_function = flatten(keras_loss_function)
     21     globals()[deeptrack_loss_function.__name__] = deeptrack_loss_function
     22 

NameError: name 'flatten' is not defined

**Comment by BenjaminMidtvedt** [comment]
See #23
