### ISSUE TITLE
Lack of descriptions in tutorial multi_particle_tracking

### ISSUE THREAD

**Issue by hsaga** [BenjaminMidtvedt/DeepTrack#29]
There is a lack of similar description as in the other tutorial. This tutorial is not very clear.

**Comment by BenjaminMidtvedt** [comment]
I will open a new branch flesh out this tutorial. However, the multi_tutorial_tracking tutorial is meant to supplement the tracking_point_particles tutorial and will generally not repeat points brought up there.
