### ISSUE TITLE
Error in tutorial track_point_particles

### ISSUE THREAD

**Issue by hsaga** [BenjaminMidtvedt/DeepTrack#31]
Error in the second last column:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-9-6904017ee4b7> in <module>
      1 G = Generator()
      2 
----> 3 model = deeptrackNetwork(input_shape=(64, 64, 1), number_of_outputs=2)
      4 
      5 # Divide position by 64 to get value between 0 and 1

NameError: name 'deeptrackNetwork' is not defined

**Comment by BenjaminMidtvedt** [comment]
Should be fixed in previous merge
