### ISSUE TITLE
Error in tutorial multi_particle_tracking_with_unet

### ISSUE THREAD

**Issue by hsaga** [BenjaminMidtvedt/DeepTrack#32]
Error in the second last cell:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-9bdc8878b852> in <module>
----> 1 model.fit(generator, epochs=20, steps_per_epoch=10)

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1276         steps_name='steps_per_epoch',
   1277         steps=steps_per_epoch,
-> 1278         validation_split=validation_split)
   1279 
   1280     # Prepare validation data.

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split)
    876         feed_input_shapes,
    877         check_batch_axis=False,  # Don't enforce the batch size.
--> 878         exception_prefix='input')
    879 
    880     if y is not None:

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    141     data = data.values if data.__class__.__name__ == 'DataFrame' else data
    142     data = [data]
--> 143   data = [standardize_single_array(x) for x in data]
    144 
    145   if len(data) != len(names):

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py in <listcomp>(.0)
    141     data = data.values if data.__class__.__name__ == 'DataFrame' else data
    142     data = [data]
--> 143   data = [standardize_single_array(x) for x in data]
    144 
    145   if len(data) != len(names):

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py in standardize_single_array(x)
     79   elif tensor_util.is_tensor(x):
     80     return x
---> 81   elif x.ndim == 1:
     82     x = np.expand_dims(x, 1)
     83   return x

AttributeError: 'generator' object has no attribute 'ndim'

**Comment by hsaga** [comment]
This is also a reoccurring error.

**Comment by BenjaminMidtvedt** [comment]
This sounds like a tensorflow/keras version error. What version are you using?

**Comment by hsaga** [comment]
tensorflow 1.1.0
keras 2.2.4

**Comment by BenjaminMidtvedt** [comment]
I will attempt to replicate, but I suggest updating tensorflow. It has now updated to 2.0, which may not be compatible with 1.0 versions.

**Comment by giovannivolpe** [comment]
Got the same error.
We need to have a robust way of dealing with this c=kind of errors for when we distribute the code.
Maybe, we should provide a virtual environment.

**Comment by BenjaminMidtvedt** [comment]
I don't think providing a virtual environment is a good idea, it'd probably just confuse most users. Since this seems to be a common issue, I'll make sure it's version compatible. Other than that, I suggest just explicitly stating a minimum required version.

What is the version of tensorflow / keras you're using?

**Comment by giovannivolpe** [comment]
An older one, but I'm now reinstalling everything.
Let me finish a few tests and then we can decide what to do
