### ISSUE TITLE
Error 2 in features_example 

### ISSUE THREAD

**Issue by hsaga** [BenjaminMidtvedt/DeepTrack#34]
In the 'Exponentiating feature with integer (**)' section:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-72266ad80aab> in <module>
      1 foo = Foo(my_property = ["bar", "baz", "qux", "quux"])
      2 
----> 3 output_image = (foo**5).resolve(input_image)

~/Documents/Projects/Neural networks/DeepTrack Benjamin/DeepTrack-master 2/deeptrack/features.py in resolve(self, image, **global_kwargs)
    115 
    116 
--> 117         image = self.get(image, **feature_input)
    118 
    119         # Add current_properties to the image the class attribute __property_verbosity__

~/Documents/Projects/Neural networks/DeepTrack Benjamin/DeepTrack-master 2/deeptrack/features.py in get(self, image, features, **kwargs)
    244     def get(self, image, features=None, **kwargs):
    245         for feature in features:
--> 246             image = feature.resolve(image, **kwargs)
    247         return image
    248 

~/Documents/Projects/Neural networks/DeepTrack Benjamin/DeepTrack-master 2/deeptrack/features.py in resolve(self, image, **global_kwargs)
    115 
    116 
--> 117         image = self.get(image, **feature_input)
    118 
    119         # Add current_properties to the image the class attribute __property_verbosity__

TypeError: get() got an unexpected keyword argument 'num_duplicates'

**Comment by BenjaminMidtvedt** [comment]
This was likely due to discrepancies in the internal ordering of dictionaries between python versions. Should be fixed as of the latest merge.
