### ISSUE TITLE
Property with iterator does not warp

### ISSUE THREAD

**Issue by giovannivolpe** [BenjaminMidtvedt/DeepTrack#44]
When calling a property with an iterator (list), it gives an error once it exhausts all elements of the list. I think it should warp to the first element instead.

See properties_example and specifically the code:

P = Property(iter([1, 2, 3, 4, 5]))
for _ in range(10):
    P.update()
    print("The current value of the property is", P.current_value)

**Comment by BenjaminMidtvedt** [comment]
Good idea!

**Comment by BenjaminMidtvedt** [comment]
This is however notoriously difficult to implement.  Once the iterator has exhausted, there is no way to retrieve it. The alternative would be to store a copy of the initial iterator, however, infinite iterators can't be copied. There is no way to distinguish an infinite iterator from a finite one. Maybe a more reasonable solution is to make it continuously output the last element of the iterator?

**Comment by giovannivolpe** [comment]
Let's make it output the last element of the iterator.
This should at least avoid throwing an error at runtime.
We should explain this explicitly int he documentation.

**Comment by BenjaminMidtvedt** [comment]
See #49
