### ISSUE TITLE
Explain calculation of pixel position in scatterers_example

### ISSUE THREAD

**Issue by giovannivolpe** [BenjaminMidtvedt/DeepTrack#46]
Explain in detail why the position is not at pixels (32, 32). Maybe, it'd be good to add an explanation how it's calculated in this specific case?

**Comment by BenjaminMidtvedt** [comment]
This is a case of convenience versus clearness. What is actually happening (which I'm not sure is what _should_ happen),  is that the particle is placed at (32, 32) correctly. Then a default 10 pixel padding is applied to the image, shifting the particle to (42, 42).  Should default padding be 0? Normally one will define an output region, thus solving this problem.

**Comment by giovannivolpe** [comment]
Let's use a 0 padding in this image for the example. Also, please, add a new cell to explain the padding in scatterers_example
