### ISSUE TITLE
Change K to backend in losses.py

### ISSUE THREAD

**Issue by giovannivolpe** [BenjaminMidtvedt/DeepTrack#54]
I'd change K to backend in losses.py, unless there is a good reason not to do it.

**Comment by BenjaminMidtvedt** [comment]
It is the variable used in [Keras examples](https://keras.io/backend/#using-the-abstract-keras-backend-to-write-new-code).  Though I don't mind changing it all that much.

**Comment by giovannivolpe** [comment]
OK, let's use K
