### ISSUE TITLE
Check resolve() and update()

### ISSUE THREAD

**Issue by giovannivolpe** [BenjaminMidtvedt/DeepTrack#76]
I have done this, and it works as expected. I'd say that

A = optics1(particle)
B = optics2(particle)
A.resolve()
B.resolve()

Will work correctly, while

A = optics1(particle)
A.resolve()
B = optics2(particle)
B.resolve()

will be incorrect. Both should of course be consistent.

**Comment by BenjaminMidtvedt** [comment]
Closing as #80 should fix this concern
